global:
  scrape_interval: 15s

rule_files:
  - alertas.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: aerohub_gateway
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: aerohub_continuidad_agente
    static_configs:
      - targets: ["continuidad-agente:9101"]
